### ISSUE TITLE
Bee Agent - Wikipedia/DuckduckGo - The generated output does not adhere to the schema.

### ISSUE THREAD

**Issue by seyhunak** [i-am-bee/bee-stack#33]
Hello. 

I am using, bee-stack (fresh from main branch) running on Ollama, llama3.2:latest as model. Running all nodes perfectly using Podman on macOS. Issue statement here is; if I create Wikipedia or DuckDuckGo bots are unable to parse response and output goes not adhere to the schema exception fires up, seems valid data not has been parsed yet.

I have attached small excerpt from bee-api Podman logs, and screenshot. 

Anyone have an idea to find out root cause?

```
{"level":"error","time":"2024-11-06T09:37:34.183Z","hostname":"05c1a7899d78","name":"bee-api","runId":"run_672b38cacd4862dbac29e79b","err":{"type":"AgentError","message":"Error has occurred!","stack":"AgentError: Error has occurred!","aggregateErrors":[{"type":"LinePrefixParserError","message":"The generated output does not adhere to the schema.\nNothing valid has been parsed yet!","stack":"LinePrefixParserError: The generated output does not adhere to the schema.\nNothing valid has been parsed yet!","aggregateErrors":[],"isFatal":true,"isRetryable":false,"context":{"lines":"","excludedLines":"","finalState":{},"partialState":{}},"name":"LinePrefixParserError"}],"isFatal":false,"isRetryable":true,"context":{},"name":"AgentError"},"msg":"Run execution failed"}
{"level":"info","time":"2024-11-06T09:37:34.187Z","hostname":"05c1a7899d78","name":"bee-api","correlationId":"34cf855d-9c24-43e2-92e1-c11956e7233b","res":{"hostname":"bee-api:4000","correlationId":"34cf855d-9c24-43e2-92e1-c11956e7233b","statusMessage":"OK","statusCode":200},"responseTime":12173.712296999991,"msg":"request completed"}

```

<img width="812" alt="Screenshot 2024-11-06 at 1 39 29 PM" src="https://github.com/user-attachments/assets/c8f9cc81-0677-4a96-810a-e5204b44beef">

**Comment by Tomas2D** [comment]
Hello @seyhunak. llama3.2 from Ollama is only 3b, which is too small for Bee to work correctly. 
The recommended model is llama3.1 (ideally 70b or bigger) or Granite soon.
