### ISSUE TITLE
Requesting a "Podman compose" version that does not exist

### ISSUE THREAD

**Issue by thomassuedbroecker** [i-am-bee/bee-stack#35]
# Problem

Requesting a "Podman compose" version that does not exist.

# Objective

Setup the basic configuration.

# Error

```sh
❗ERROR: None of compose command versions meets the required version 2.29.
❗       Found versions: podman compose (2.26.1)
❗       Please (re)install a supported runtime
```

This version doesn't exist: `https://github.com/containers/podman-compose/releases`
You mean `Docker Compose version v2.26.1`.

# Steps to reproduce

I followed the instruction to the current repo.

```sh
git clone https://github.com/i-am-bee/bee-stack.git
cd bee-stack
# Run setup script to configure LLM provider and start the stack
./bee-stack.sh setup
```

```sh
./bee-stack.sh setup
>>>> Executing external compose provider "/usr/local/bin/docker-compose". Please see podman-compose(1) for how to disable this message. <<<<

❗ERROR: None of compose command versions meets the required version 2.29.
❗       Found versions: podman compose (2.26.1)
❗       Please (re)install a supported runtime

For installation instructions, see:
- Podman desktop: https://podman.io
  ⚠️ install using the official installer (not through package manager like brew, apt, etc.)
  ⚠️ use rootful machine (default)
  ⚠️ use docker compatibility mode
- Rancher desktop: https://rancherdesktop.io
- Docker desktop: https://www.docker.com/
```

# Trying tow options to solve the problem

1. Reinstall installation 
- Podman desktop: https://podman.io
  ⚠️ install using the official installer (not through package manager like brew, apt, etc.)
  ⚠️ use rootful machine (default)
  ⚠️ use docker compatibility mode

2. I followed this steps Problem solved with:
`https://github.com/podman-desktop/podman-desktop/discussions/6553`

# Result both options didn't work

```sh
Client:       Podman Engine
Version:      5.2.5
Server:       Podman Engine
Version:      5.2.5
```

```sh
podman compose version 
>>>> Executing external compose provider "/usr/local/bin/docker-compose". Please see podman-compose(1) for how to disable this message. <<<<

Docker Compose version v2.26.1
```

**Comment by jezekra1** [comment]
This is the problem

```
> podman compose version 
Docker Compose version v2.26.1
```

We require version 2.29+ (please update podman to newest version)

**Comment by thomassuedbroecker** [comment]
@jezekra1 
I know that this is the problem: The 'Podman Desktop'  installation comes with the *Docker Compose version v2.26.1*. 
As you wrote in the instructions using the 'Podman Desktop'  installation and use the related Compose.

I wanted to follow the instruction is a [podman issue](https://github.com/podman-desktop/podman-desktop/discussions/6553) to update Docker Compose version alone and bind it to Podman and this didn't work:

This is the current stable Podman version.

```sh
Client:       Podman Engine
Version:      5.2.5
API Version:  5.2.5
Go Version:   go1.23.2
Git Commit:   10c5aa720d59480bc7edad347c1f5d5b75d4424f
Built:        Wed Oct 23 19:49:37 2024
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      5.2.5
API Version:  5.2.5
Go Version:   go1.22.7
Built:        Fri Oct 18 02:00:00 2024
OS/Arch:      linux/arm64
```

**Comment by thomassuedbroecker** [comment]
@jezekra1 Thanks!
