### ISSUE TITLE
Document memory requirement to run stack

### ISSUE THREAD

**Issue by mmurad2** [i-am-bee/bee-stack#40]
**Bug description**
I wasn't able to run the stack because my memory configuration on Podman Desktop was too low. It worked when I increased it.

**Desired solution**
Document memory requirements as part of prerequisites before getting started.

**Comment by psschwei** [comment]
Out of curiosity, what did you increase it to to get it to work?

**Comment by mmurad2** [comment]
I increased it to 8gb from 2gb (default), I doubt it needs that much space though.

**Comment by psschwei** [comment]
I'll investigate this one

**Comment by jezekra1** [comment]
We have this in the README:
⚠️ IMPORTANT: Make sure your VM has at least 6GB of RAM configured

**Comment by psschwei** [comment]
Fixed in https://github.com/i-am-bee/bee-stack/commit/cadbdd4db07855a467b3b1d02ced904a7213b95a
