### ISSUE TITLE
Bug - Running with OpenAI

### ISSUE THREAD

**Issue by mmurad2** [i-am-bee/bee-stack#5]
**Description**
Was unable to run the bee-stack using openAI credentials.

**Additional requirements**
Update .env file to include all LLM inference providers supported.

**Comment by aevo98765** [comment]
https://github.com/i-am-bee/bee-stack/pull/15

**Comment by aevo98765** [comment]
Hey @jezekra1, I had the same issue and came up wit this solution https://github.com/i-am-bee/bee-stack/pull/15
