### ISSUE TITLE
Provide logs for debugging issues

### ISSUE THREAD

**Issue by yoda-aus** [i-am-bee/bee-stack#51]
Allowing users to capture detailed information about the system's state, including timestamps, relevant variables, function calls, and other error messages will be useful and a valuable time saving.

**Comment by Tomas2D** [comment]
Isn't `docker compose logs bee-api` enough?

**Comment by jezekra1** [comment]
I added `./bee-stack.sh logs` that will package the logs in a zip file and instruct users to create an issue on github in the PR #55 . cc @mmurad2.
