### ISSUE TITLE
"Internal server error" on bee UI

### ISSUE THREAD

**Issue by yoda-aus** [i-am-bee/bee-stack#56]
Hi, 
On my mac workstation, on trying to reach the bee-ui url http://localhost:3000/ I get a "Internal server error" on the browser.
The attached logs indicated in the "bee-ui.log" show - 

" TypeError: fetch failed
bee-ui-1  |     at node:internal/deps/undici/undici:12345:11
bee-ui-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
bee-ui-1  |   cause: Error: getaddrinfo EAI_AGAIN bee-api
bee-ui-1  |       at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
bee-ui-1  |       at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
bee-ui-1  |     errno: -3001,
bee-ui-1  |     code: 'EAI_AGAIN',
bee-ui-1  |     syscall: 'getaddrinfo',
bee-ui-1  |     hostname: 'bee-api'
bee-ui-1  |   }
bee-ui-1  | }"

Other logs:
<img width="767" alt="Rancher" src="https://github.com/user-attachments/assets/fdcc702a-71aa-4611-b290-5bcc408b117f">
<img width="605" alt="Colima" src="http
<img width="500" alt="Services started" src="https://github.com/user-attachments/assets/1142563d-b22f-4ccd-b731-cb9b7c7cd68e">
<img width="917" alt="UI Error" src="https://github.com/user-attachments/assets/b99bc026-6351-4c7d-8c74-a410d7c42e19">
s://github.com/user-attachments/assets/a272500d-0672-4cb2-954c-0ff7bf721dfa">

[2024-12-01_1700S.zip](https://github.com/user-attachments/files/17981840/2024-12-01_1700S.zip)

**Comment by jezekra1** [comment]
First step is to uninstall colima and install Rancher desktop instead as discussed on slack

Closing this as colima is not one of supported runtimes. Most likely you don't have enough RAM configured for colima. Feel free to reopen later.

Please go through the troubleshooting guide and make sure you have at least 8GB RAM configured for the Rancher VM:
https://github.com/i-am-bee/bee-stack/blob/main/docs/troubleshooting.md

EDIT: Reported as working with Rancher
