### ISSUE TITLE
Bee UI - Example Assistant

### ISSUE THREAD

**Issue by seyhunak** [i-am-bee/bee-stack#7]
Hello 

Installed bee-stack with following instructions on README file, all 11 of 11 services are up and healthy in Docker. But getting failure below and not able to see error description in the logs, what might be the issue, root cause of problem?

<img width="862" alt="Screenshot 2024-10-26 at 8 48 50 PM" src="https://github.com/user-attachments/assets/be112f4b-9f23-408b-b070-5a87d0b309de">

**Comment by jezekra1** [comment]
Did you use the correct backend provider and api key in the `.env` file?

**Comment by seyhunak** [comment]
Thanks for respond @jezekra1 

Yes. As like below setup configured in .env file, I can able to run all 11/11 services through Docker Compose successfully. But, issue is persist, any advise?

.env - Actual keys are masked.
LLM_BACKEND=watsonx
EMBEDDING_BACKEND=watsonx
WATSONX_PROJECT_ID=xxx
WATSONX_API_KEY=cpd-apikey-xxx
WATSONX_REGION=eu-de

**Comment by jezekra1** [comment]
I see, it's probably the region, which was missing from the env:
https://github.com/i-am-bee/bee-stack/pull/8

**Comment by jezekra1** [comment]
can you `git pull` and try again?

**Comment by seyhunak** [comment]
Thanks @jezekra1  able to run Bee agents in locally, switched from WatsonX to Ollama as well worked.
