### ISSUE TITLE
Bee UI - stack using podman, macos, ollama - assistant fails

### ISSUE THREAD

**Issue by planetf1** [i-am-bee/bee-stack#9]
I’m trying to run the bee stack under podman/macOS. (docker-compose is installed as the podman compose provider)

I have ollama running locally (homebrew, has gpu acceleration for inference), with various models including llama3.2:latest loaded

I’ve set `~/.homebrew/brew.env` to include `OLLAMA_HOST=0.0.0.0` to ensure ollama listens on all interfaces (ie this is for my local machine serving ollama models)

My `.env` (same directory as the compose yaml) includes:
```
#LLM_BACKEND=watsonx
LLM_BACKEND=ollama
EMBEDDING_BACKEND=ollama
WATSONX_PROJECT_ID=
WATSONX_API_KEY=
WATSONX_REGION=us-south
# Ollama
OLLAMA_HOST=http://host.containers.internal:11434/
OLLAMA_MODEL="llama3.2:latest"
```
The intent here is to use ollama locally, not watsonx

I bring up the environment with `podman compose --profile all up -d`

However when trying to use the UI at http://localhost:3000/ ie bee assistant, I’ll just get 
```
An error occurred [cause]: Error: Internal server error
```
I can connect to one of the containers and check network connectivity ie:
```
➜  bee-stack git:(main) podman ps | grep api
9541b364112c  docker.io/iambeeagent/bee-api:0.0.5       /bin/sh -c  outpu...  5 minutes ago  Up 5 minutes (healthy)            0.0.0.0:4000->4000/tcp, 4000/tcp                                       bee-stack-bee-api-1
➜  bee-stack git:(main) podman exec 9541b364112c nc -zv host.containers.internal 11434
host.containers.internal (192.168.127.254:11434) open
➜  bee-stack git:(main)
```
It turns out the api server is throwing an error getting to ollama
```
{"level":"error","time":"2024-10-28T21:37:52.633Z","hostname":"9541b364112c","name":"bee-api","queueName":"runs","job":{"id":"run_67200430a3d0085099bd33c0","name":"runs","failedReason":"fetch failed","data":{"runId":"run_67200430a3d0085099bd33c0"}},"err":{"type":"TypeError","message":"fetch failed: connect ECONNREFUSED 127.0.0.1:11434","stack":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:12502:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async post (file:///app/node_modules/.pnpm/ollama@0.5.9/node_modules/ollama/dist/shared/ollama.133b951a.mjs:112:20)\n    at async Ollama.show (file:///app/node_modules/.pnpm/ollama@0.5.9/node_modules/ollama/dist/shared/ollama.133b951a.mjs:383:22)\n    at OllamaChatLLM.meta (/app/node_modules/.pnpm/bee-agent-framework@0.0.33_@bufbuild+protobuf@1.10.0_@googleapis+customsearch@3.2.0_@grpc+grp_mfkxw3ngujdfeym4yi6s5rae6y/node_modules/bee-agent-framework/src/adapters/ollama/chat.ts:147:19)\n    at TokenMemory.add (/app/node_modules/.pnpm/bee-agent-framework@0.0.33_@bufbuild+protobuf@1.10.0_@googleapis+customsearch@3.2.0_@grpc+grp_mfkxw3ngujdfeym4yi6s5rae6y/node_modules/bee-agent-framework/src/memory/tokenMemory.ts:84:20)\n    at TokenMemory.addMany (/app/node_modules/.pnpm/bee-agent-framework@0.0.33_@bufbuild+protobuf@1.10.0_@googleapis+customsearch@3.2.0_@grpc+grp_mfkxw3ngujdfeym4yi6s5rae6y/node_modules/bee-agent-framework/src/memory/base.ts:39:13)\n    at async executeRun (file:///app/dist/runs/execution/execute.js:75:3)\n    at async file:///app/dist/runs/jobs/runs.queue.js:49:7\n    at Worker.processJob (/app/node_modules/.pnpm/bullmq@5.8.1/node_modules/bullmq/src/classes/worker.ts:786:22)\ncaused by: Error: connect ECONNREFUSED 127.0.0.1:11434\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)"},"msg":"Job failed"}
```

But this is on **127.0.0.1:11434** not the host I specified ( **http://host.containers.internal:11434/** )

Did I get the configuration wrong?

Perhaps there is an issue with passing through the environment and ignoring my configuration?. 

I did also try using `podman-compose` as the provider with quite different results (possibly the subject of another issue?)
```
➜  bee-stack git:(main) podman compose --profile all up -d
>>>> Executing external compose provider "/opt/homebrew/bin/podman-compose". Please see podman-compose(1) for how to disable this message. <<<<

9731c7f63b2227c9b3a8e083e1bc00a0812cd5e03f6b82f72a93698185f496f4
Error: crun: setrlimit `RLIMIT_NPROC`: Operation not permitted: OCI permission denied
Error: unable to start container "c097aa00e184453aff6b8881787e6e073ec21db42d28c1e57f26b68dc4b95c82": crun: setrlimit `RLIMIT_NPROC`: Operation not permitted: OCI permission denied
abb770105d2e5cc5988aaa54a830f47e19f94d7e22d5870da6eba6d88fe92ef1
bf330d3111f374aab42791c9834e5700b762f80330c97bc759f700cbbd3cde8d
92d6d3310ef257c620322ca066293213f17a3f909445985db67b2db56b6d2cf6
f26e4469ef74de3cdf1021a59b4ad3617b459cc325f8e4b07fb221ce6cd0192d
81bd82e5a80a9fa2f3a543b8b02d4beac8daeb9961436372ae70992f28b6f04b
08edd6a8193ed7bd94dcba6b844ea089e30b2e9f4195a686261e95297629a9c8
ed2ac5d34554312a9c105f2177f908ed439cc406cbd70d7530f789c10a86aeed
44c922a2af84723d4986e24c81bef6465fdc77ceda48154fee6d0905a8d3d899
057db966d4ec183a8f43854352406475db02e4b4f4e1ca4d01412ced8656bf2c
8630307b792d5eae20bccbe6f653f10309d6f6434621bd74b0d86273ac3271db
```

Note: Could be Similar to #7

**Comment by planetf1** [comment]
Using the docker-compose provider, the log does seem to indicate the env file is being passed ie with log-level=debug:
```
DEBU[0000] Executing compose provider (/opt/homebrew/bin/docker-compose --env-file=.env --profile all up -d) with additional env DOCKER_HOST=unix:///var/folders/y0/dtxnsmfs0sz8_01kd0hhfjrc0000gn/T/podman/podman-machine-default-api.sock DOCKER_BUILDKIT=0 DOCKER_CONFIG=
```

**Comment by planetf1** [comment]
Ah! Found the issue.

The OLLAMA_HOST variable is not getting passed in the `environment` section of the compose file into the api server.

**Comment by planetf1** [comment]
I'll try a fix and can create a PR

**Comment by planetf1** [comment]
After fix:
```
➜  bee-stack git:(main) ✗ docker exec 356b70ee7143 env | grep ollama
LLM_BACKEND=ollama
EMBEDDING_BACKEND=ollama
➜  bee-stack git:(main) ✗ docker exec 356b70ee7143 env | grep OLLAMA
OLLAMA_HOST=http://host.containers.internal:11434
OLLAMA_MODEL=llama3.2:latest
```

However still seeing logs from the api server
```
: connect ECONNREFUSED 127.0.0.1:11434","stack":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:12502:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    
```

**Comment by planetf1** [comment]
I see some fixes have been made to utilize this env var recently, presumably not in the image being used in the current compose yaml **iambeeagent/bee-api:0.0.5**

Additionally the bee-api is using `OLLAMA_URL`. Tried also passing this through, and was able to get the bee stack UI working for a simple dialogue. I didn't however see where the model was specified (first time looking at code).

**Comment by planetf1** [comment]
Have updated PR, but this may be work in progress from the core devs, so just updating as an example which seems to work. There are other potential issues such as embedding. (update - that works after `ollama pull nomic-embed-text`)

**Comment by jezekra1** [comment]
Unfortunately `host.containers.internal` is a podman-specific feature, we'll have to find a more generic solution working in all container runtimes, I'll look into this.

**Comment by planetf1** [comment]
> Unfortunately `host.containers.internal` is a podman-specific feature, we'll have to find a more generic solution working in all container runtimes, I'll look into this.

Correct, but as far as the bee code goes, it's just a hostname. If networking is configured appropriately it could be a regular DNS-resolved hostname, but there are a myriad of ways that networking can be setup in podman and docker  (in some ways it's easier in k8s)

docker has `host.docker.internal`. In fact it looks as if, since mid 2023, this is now standard for podman too (see [issue](https://github.com/containers/podman/issues/19361)) so we could update to just state that

The above relates to the readme PR #11 -- there's also a separate PR #10 on the additional variables that need passing from compose.
